linters:
  Indentation:
    enabled: false
    character: tab
    width: 1

  DeclarationOrder:
    enabled: false

  Comment:
    enabled: true
    allowed: '/*doc'

  IdSelector:
    enabled: false

  VendorPrefix:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  NestingDepth:
    max_depth: 4
    ignore_parent_selectors: true

exclude:
  - '**/*.css'